### ISSUE TITLE
请教一下，报这个错是什么问题，谢谢

### ISSUE THREAD

**Issue by hnlijin** [fairygui/FairyGUI-dom#6]
ERROR in ./test/src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:43193:18)
    at E:\Github\FairyGUI-dom\node_modules\ts-loader\dist\servicesHost.js:613:77
    at E:\Github\FairyGUI-dom\node_modules\ts-loader\dist\servicesHost.js:131:142
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (E:\Github\FairyGUI-dom\node_modules\ts-loader\dist\servicesHost.js:131:125)
    at actualResolveTypeReferenceDirectiveNamesWorker (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:118257:163)
    at resolveTypeReferenceDirectiveNamesWorker (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:118557:26)
    at processTypeReferenceDirectives (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:120054:31)
    at findSourceFileWorker (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:119939:21)
    at findSourceFile (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:119791:26)
    at E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:119740:85
    at getSourceFileFromReferenceWorker (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:119706:34)
    at processSourceFile (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:119740:13)
    at processTypeReferenceDirectiveWorker (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:120085:21)
    at processTypeReferenceDirective (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:120070:13)
    at Object.createProgram (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:118360:21)
    at synchronizeHostData (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:167688:26)
    at Object.getProgram (E:\Github\FairyGUI-dom\node_modules\typescript\lib\typescript.js:167802:13)
    at Object.initializeInstance (E:\Github\FairyGUI-dom\node_modules\ts-loader\dist\instances.js:193:84)
    at successLoader (E:\Github\FairyGUI-dom\node_modules\ts-loader\dist\index.js:28:17)
    at Object.loader (E:\Github\FairyGUI-dom\node_modules\ts-loader\dist\index.js:25:5)

**Comment by hnlijin** [comment]
nodejs v16.15.0

**Comment by hnlijin** [comment]
终于自己解决了，更改了这些版本

-    "ts-loader": "^7.0.4",
+    "ts-loader": "^8.4.0",
     "typescript": "^4.2.3",
-    "webpack": "^4.43.0",
+    "webpack": "^5.0.0",
