### ISSUE TITLE
构建没成功啊！

### ISSUE THREAD

**Issue by scc172fly** [fairygui/FairyGUI-dom#9]
G:\GitHub\FairyGUI\FairyGUI-dom>gulp buildJs
{ Error: Cannot find module 'rollup'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\GitHub\FairyGUI\FairyGUI-dom\gulpfile.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

**Comment by scc172fly** [comment]
有没有人写个教程啊，没跑起来。

**Comment by xiaoguzhu** [comment]
先npm install。然后npm run build source或者npm run build test
